name: "Snyk Code Scan"
on:
  push:
    branches:
      - master
jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: e68e9955-4949-4c24-ae45-d04cc5cb5b53
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v1
      # Install and Authenticate to Snyk
      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth e68e9955-4949-4c24-ae45-d04cc5cb5b53
      # Run Snyk Code
      - name: Run Snyk Code
        run: |
          snyk code test --severity-threshold=high
        continue-on-error: true
